### PR TITLE
Remove unused subroutines

### PR DESCRIPTION
**Pull request by nicolasbock**
This change removes unused code.

---
This change is [Reviewable](https://reviewable.io/reviews/lanl/qmd-progress/73)

### CODE REVIEW

**Comment by cnegre** [comment]
@nicolasbock Can we integrate this change?

**Comment by cnegre** [comment]
Excellent! Thanks

**Comment by cnegre** [comment]
@nicolasbock Hi Nick, 
Any clue why the checks are not passing with this new commit?

**Comment by cnegre** [comment]
@nicolasbock  I see why

**Comment by nicolasbock** [comment]
I don't know. I think the MD test is not reproducing the same 
numbers as it did before. I haven't looked at the results in 
detail though.

**Pull request merged**
